// Auto-generated by scripts/build-projects.ts — do not edit directly.
// Source: content/projects/*.yaml
import { defineProjects } from "./project-schema";

export const projectDossiers = defineProjects(
[
  {
    "slug": "hyperion",
    "accent": "#3bb5a5",
    "title": "Hyperion",
    "subtitle": "Agentic Trading",
    "summary": "An agentic trading system for Hyperliquid that translates plain-language strategies into executable orders, bounded by deterministic risk guards, paper-trade verification, and a real-time signal terminal.",
    "description": "A full-stack trading platform where an LLM agent translates plain language into strategy JSON, a deterministic interpreter executes it with seven risk guards and emergency unwind, and a signal terminal streams conviction-scored alerts from Hyperliquid and Bybit. Runs unattended or with a human in the loop.",
    "overview": [
      "Three-layer control model: the agent parses intent, the human confirms or steps aside, the deterministic interpreter owns execution. Seven pre-execution guards and an emergency unwind sit between the agent and real capital. Paper-trade mode runs strategies against live data before any money moves.",
      "The signal terminal scans Hyperliquid and Bybit continuously, scores alerts by conviction, and pushes them over WebSocket and Telegram. Portfolio branches let you simulate hypothetical positions against your actual book with full margin math. The monorepo covers shared types, SDK wrappers, strategy interpretation, risk checks, market surveillance, paper-trade simulation, a React cockpit, a TUI dashboard, and an Astro site. Daemon communicates over Unix sockets with a WebSocket bridge for the web frontend."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/hyperion"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/hyperagent"
      }
    ],
    "techStack": [
      "TypeScript",
      "React",
      "Hono",
      "Bun",
      "WebSocket"
    ],
    "layout": "standard",
    "status": "Active build",
    "year": "2026"
  },
  {
    "slug": "meridian",
    "accent": "#4cb862",
    "title": "Meridian",
    "subtitle": "A cartographic interface",
    "summary": "A globe-scale map interface for comparing and visualizing global metrics and generating city intelligence briefs",
    "description": "Global metrics as overlays on a 3D MapLibre globe — compare cities at a glance. An OpenAI-powered agent generates city intelligence briefs and builds multi-city itineraries from a chat interface.",
    "overview": [
      "Each metric is a surface layer on the globe. MapLibre GL JS handles cartographic rendering, deck.gl composes data overlays, and a Hono backend serves normalized metric surfaces. Geographic context and metric distribution in one view instead of static comparison tables.",
      "The atlas is the primary interface. A chat agent generates city briefs, compares regions, and builds itineraries. Zustand keeps the globe, overlays, and chat state in sync across a session."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/meridian"
      },
      {
        "label": "Live demo",
        "href": "https://meridian-cartography.onrender.com"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/meridian"
      }
    ],
    "techStack": [
      "MapLibre GL JS",
      "deck.gl",
      "Hono",
      "OpenAI",
      "Zustand"
    ],
    "layout": "wide",
    "status": "In development",
    "year": "2026"
  },
  {
    "slug": "lexis-editorial-companion",
    "accent": "#e08a3c",
    "title": "Lexis",
    "subtitle": "Editorial Intelligence",
    "summary": "An AI-powered editorial rewriting tool that streams improved prose with inline change highlighting, alternative phrasings, and interactive editing workflows.",
    "description": "Lexis takes prose input and streams a stylistically improved rewrite using OpenAI or Anthropic models. Every change shows up inline with visual diffs, alternative phrasings, and full undo/redo. It is an editorial partner for serious drafting, not an autocomplete layer.",
    "overview": [
      "The project is an editorial system, not a generic assistant. It supports rewrites, tonal calibration, structural decisions, and sharper sentence-level judgment. Each change is surfaced inline with visual diffs so the writer can accept, reject, or refine every edit.",
      "Its personality is companionable but exacting: a discerning editor in the room rather than a soft productivity wrapper. A React frontend pairs with a FastAPI backend that streams rewrites in real time, deployed as a unified Vercel application."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/lexis-editorial-companion"
      },
      {
        "label": "Live demo",
        "href": "https://lexis-main.vercel.app/"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/lexis-editorial"
      }
    ],
    "techStack": [
      "React",
      "FastAPI",
      "OpenAI",
      "Vercel"
    ],
    "layout": "standard",
    "status": "Active build",
    "year": "2026"
  },
  {
    "slug": "swarm",
    "accent": "#6b8fb5",
    "title": "Swarm",
    "subtitle": "Agent Orchestrator",
    "summary": "A provider- and harness-agnostic AI agent orchestrator that lets you define DAG-based workflows of AI agents across any combination of agentic CLIs and a native ReAct loop.",
    "description": "Swarm lets you define directed acyclic graphs of AI agents that run on any combination of external agentic CLI runtimes, Claude Code, Droid, OpenCode, aider, codex, or a built-in native ReAct loop, with parallel scheduling, cancellation propagation, a real-time web dashboard, and SQLite-backed event logging with time-travel replay.",
    "overview": [
      "The architecture is provider- and harness-agnostic. Agents in a DAG can run on different CLI runtimes simultaneously, and the orchestrator handles scheduling, dependency resolution, and cancellation propagation across the graph. A built-in ReAct loop provides a fallback when no external harness is available. The event bus and projection system capture every agent action for real-time dashboard rendering and historical replay.",
      "The web dashboard uses React Flow for DAG visualization with a terminal panel for live output and a time-travel scrubber for replaying past runs. The daemon exposes an HTTP and WebSocket API backed by bun:sqlite for event persistence. The monorepo separates core interfaces, CLI adapters, daemon server, dashboard SPA, and CLI binary into isolated workspace packages."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/swarm"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/swarm"
      }
    ],
    "techStack": [
      "TypeScript",
      "React Flow",
      "SQLite",
      "WebSocket",
      "Bun"
    ],
    "layout": "standard",
    "status": "Prototype",
    "year": "2026"
  },
  {
    "slug": "equilibria",
    "accent": "#e4a853",
    "title": "Equilibria",
    "subtitle": "Algorithmic Flatcoin",
    "summary": "An algorithmic flatcoin with built-in tranching and supply-sensitive stability mechanics.",
    "description": "A monetary systems project about balance, incentives, and structural resilience. Stability is a designed mechanism, not a branding claim.",
    "overview": [
      "Market-aware behavior paired with tranche design — exposure gets shaped instead of flattened into a single risk profile."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/equilibria"
      },
      {
        "label": "Live demo",
        "href": "https://equilibria.cash"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/equilibria-protocol"
      }
    ],
    "techStack": [],
    "layout": "standard",
    "status": "In development",
    "year": "2026"
  },
  {
    "slug": "noted",
    "accent": "#e4c853",
    "title": "Noted",
    "subtitle": "Knowledge Graph",
    "summary": "A client-side knowledge graph that writes Markdown notes, auto-embeds them via OpenAI, and infers semantic relationships to build a navigable graph visualization.",
    "description": "Noted v2 is a knowledge graph and note-taking system where notes are connected via directed edges, supports, contradicts, elaborates, references, relates-to, and grouped into regions. An agent pipeline runs after each save to embed content via OpenAI and infer semantic edges automatically.",
    "overview": [
      "The system treats knowledge as a graph of interconnected atomic notes, not a flat file hierarchy. Each note is typed, thought or source, connected via directed semantic edges, and grouped into regions. After each save, an agent pipeline embeds the content via OpenAI's text-embedding-3-small model and infers semantic edges, building the graph automatically as you write.",
      "The editor is built on TipTap, ProseMirror, with rich extensions for links, tasks, markdown, and drag handling. Graph visualization uses React Flow and react-force-graph-2d for navigating the knowledge space. All data lives locally in IndexedDB via Dexie. No server required. The application runs as a client-side Vite SPA deployed on Vercel."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/noted"
      },
      {
        "label": "Live demo",
        "href": "https://noted-two-azure.vercel.app/"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/noted"
      }
    ],
    "techStack": [
      "React",
      "TipTap",
      "React Flow",
      "OpenAI",
      "Dexie",
      "Vite"
    ],
    "layout": "standard",
    "status": "In development",
    "year": "2026"
  }
]
);
