// Auto-generated by scripts/build-projects.ts — do not edit directly.
// Source: content/projects/*.yaml
import { defineProjects } from "./project-schema";

export const projectDossiers = defineProjects(
[
  {
    "slug": "hyperion",
    "accent": "#3bb5a5",
    "title": "Hyperion",
    "subtitle": "Agentic Trading",
    "summary": "An agentic trading system for Hyperliquid that translates plain-language strategies into executable orders, bounded by deterministic risk guards, paper-trade verification, and a real-time signal terminal.",
    "description": "Hyperion is a full-stack trading platform. An LLM agent translates natural language into strategy JSON, a deterministic interpreter executes with seven pre-execution risk guards and emergency unwind, and a signal terminal aggregates live market data from Hyperliquid and Bybit with conviction-scored alerts via WebSocket and Telegram. It supports paper-trading against live data before committing real capital and can run unattended.",
    "overview": [
      "The architecture is a three-layer control model. The LLM agent parses intent and generates strategy JSON. The human confirms, or delegates to unattended mode. The deterministic interpreter owns execution. Paper-trade mode lets users validate strategies against live market data before committing real capital. Seven pre-execution risk guards and an emergency unwind function ensure the agent cannot bypass safety constraints.",
      "The signal terminal continuously scans market data from Hyperliquid and Bybit, applies technical indicators, and produces conviction-scored alerts via WebSocket and Telegram. Portfolio branches let traders simulate hypothetical positions alongside their actual portfolio with full margin math. The monorepo spans workspace packages for shared types, SDK wrappers, strategy interpretation, risk checks, market surveillance, paper-trade simulation, a React web cockpit, a TUI dashboard, and an Astro marketing site. The daemon communicates over Unix sockets with a WebSocket bridge for the web frontend."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/hyperion"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/hyperagent"
      }
    ],
    "techStack": [
      "TypeScript",
      "React",
      "Hono",
      "Bun",
      "WebSocket"
    ],
    "layout": "standard",
    "status": "Active build",
    "year": "2026"
  },
  {
    "slug": "meridian",
    "accent": "#4cb862",
    "title": "Meridian",
    "subtitle": "Nomadic Intelligence",
    "summary": "A globe-scale discovery tool that maps weather comfort, cost of living, internet speed, and other metrics onto an interactive 3D globe, with an AI agent that writes city briefs and trip plans.",
    "description": "Meridian visualizes global metrics as overlays on a 3D MapLibre globe so you can compare cities at a glance. An OpenAI-powered agent generates city intelligence briefs and builds multi-city itineraries from a chat interface.",
    "overview": [
      "Each metric is a surface layer on the globe. MapLibre GL JS handles the cartographic rendering, deck.gl composes data overlays, and a Hono backend serves normalized metric surfaces. You get geographic context and metric distribution in one view instead of static comparison tables.",
      "The atlas is the primary interface. An OpenAI-powered chat agent can generate city briefs, compare regions, and build itineraries. Zustand keeps the globe, overlays, and chat state in sync across a single session."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/meridian"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/meridian"
      },
      {
        "label": "Live demo",
        "href": "https://meridian-cartography.onrender.com"
      }
    ],
    "techStack": [
      "MapLibre GL JS",
      "deck.gl",
      "Hono",
      "OpenAI",
      "Zustand"
    ],
    "layout": "wide",
    "status": "In development",
    "year": "2026"
  },
  {
    "slug": "lexis-editorial-companion",
    "accent": "#e08a3c",
    "title": "Lexis Editorial Companion",
    "subtitle": "Editorial Intelligence",
    "summary": "An AI-powered editorial rewriting tool that streams improved prose with inline change highlighting, alternative phrasings, and interactive editing workflows.",
    "description": "Lexis takes prose input and streams a stylistically improved rewrite using OpenAI or Anthropic models. Every change shows up inline with visual diffs, alternative phrasings, and full undo/redo. It is an editorial partner for serious drafting, not an autocomplete layer.",
    "overview": [
      "The project is an editorial system, not a generic assistant. It supports rewrites, tonal calibration, structural decisions, and sharper sentence-level judgment. Each change is surfaced inline with visual diffs so the writer can accept, reject, or refine every edit.",
      "Its personality is companionable but exacting: a discerning editor in the room rather than a soft productivity wrapper. A React frontend pairs with a FastAPI backend that streams rewrites in real time, deployed as a unified Vercel application."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/lexis-editorial-companion"
      },
      {
        "label": "Live demo",
        "href": "https://lexis-main.vercel.app/"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/lexis-editorial"
      }
    ],
    "techStack": [
      "React",
      "FastAPI",
      "OpenAI",
      "Vercel"
    ],
    "layout": "standard",
    "status": "Active build",
    "year": "2026"
  },
  {
    "slug": "swarm",
    "accent": "#6b8fb5",
    "title": "Swarm",
    "subtitle": "Agent Orchestrator",
    "summary": "A provider- and harness-agnostic AI agent orchestrator that lets you define DAG-based workflows of AI agents across any combination of agentic CLIs and a native ReAct loop.",
    "description": "Swarm lets you define directed acyclic graphs of AI agents that run on any combination of external agentic CLI runtimes, Claude Code, Droid, OpenCode, aider, codex, or a built-in native ReAct loop, with parallel scheduling, cancellation propagation, a real-time web dashboard, and SQLite-backed event logging with time-travel replay.",
    "overview": [
      "The architecture is provider- and harness-agnostic. Agents in a DAG can run on different CLI runtimes simultaneously, and the orchestrator handles scheduling, dependency resolution, and cancellation propagation across the graph. A built-in ReAct loop provides a fallback when no external harness is available. The event bus and projection system capture every agent action for real-time dashboard rendering and historical replay.",
      "The web dashboard uses React Flow for DAG visualization with a terminal panel for live output and a time-travel scrubber for replaying past runs. The daemon exposes an HTTP and WebSocket API backed by bun:sqlite for event persistence. The monorepo separates core interfaces, CLI adapters, daemon server, dashboard SPA, and CLI binary into isolated workspace packages."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/swarm"
      }
    ],
    "techStack": [
      "TypeScript",
      "React Flow",
      "SQLite",
      "WebSocket",
      "Bun"
    ],
    "layout": "standard",
    "status": "Prototype",
    "year": "2026"
  },
  {
    "slug": "equilibria",
    "accent": "#e4a853",
    "title": "Equilibria",
    "subtitle": "Algorithmic Flatcoin",
    "summary": "An algorithmic flatcoin with built-in tranching and supply-sensitive stability mechanics.",
    "description": "Equilibria is a monetary systems project about balance, incentives, and structural resilience. Stability is a designed mechanism, not a branding claim.",
    "overview": [
      "The system pairs market-aware behavior with tranche design so exposure can be shaped instead of flattened into a single risk profile.",
      "Its presentation emphasizes symmetry, measured movement, and engineered equilibrium without losing the site's visual edge."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/equilibria"
      },
      {
        "label": "Live demo",
        "href": "https://equilibria.cash"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/equilibria-protocol"
      }
    ],
    "techStack": [],
    "layout": "standard",
    "status": "In development",
    "year": "2026"
  },
  {
    "slug": "routines",
    "accent": "#9b8ab8",
    "title": "Routines",
    "subtitle": "Life Operating System",
    "summary": "A personal life operating system combining a CLI bridge for Claude Routines, a deterministic decision engine across seven quality-of-life dimensions, and an LLM-maintained knowledge wiki.",
    "description": "Routines is a triad of personal productivity tools. claude-routiner, cr, triggers Claude Code Routines from the terminal. lifeOS evaluates life decisions by scoring them against seven dimensions, health, wealth, relationships, growth, environment, time freedom, meaning, and comparing against future-self attractor states. The wiki maintains a persistent knowledge base in Obsidian-compatible markdown.",
    "overview": [
      "The system orchestrates an autonomous life-improvement pipeline. claude-routiner triggers Claude Code Routines from the terminal. lifeOS evaluates life decisions by scoring them against seven dimensions and comparing against future-self attractor states. The wiki maintains a persistent knowledge base in Obsidian-compatible markdown with wikilinks and Dataview queries.",
      "Results surface via Telegram so insights arrive without active monitoring. The decision engine uses a deterministic scoring model, no LLM hallucination in the evaluation itself, while the wiki leverages LLM maintenance for keeping knowledge current. Together they form a continuous loop: observe, evaluate, act, record."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/routines"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/life-os"
      }
    ],
    "techStack": [
      "TypeScript",
      "Claude",
      "Telegram",
      "Obsidian"
    ],
    "layout": "standard",
    "status": "Active build",
    "year": "2026"
  },
  {
    "slug": "noted",
    "accent": "#e4c853",
    "title": "Noted",
    "subtitle": "Knowledge Graph",
    "summary": "A client-side knowledge graph that writes Markdown notes, auto-embeds them via OpenAI, and infers semantic relationships to build a navigable graph visualization.",
    "description": "Noted v2 is a knowledge graph and note-taking system where notes are connected via directed edges, supports, contradicts, elaborates, references, relates-to, and grouped into regions. An agent pipeline runs after each save to embed content via OpenAI and infer semantic edges automatically.",
    "overview": [
      "The system treats knowledge as a graph of interconnected atomic notes, not a flat file hierarchy. Each note is typed, thought or source, connected via directed semantic edges, and grouped into regions. After each save, an agent pipeline embeds the content via OpenAI's text-embedding-3-small model and infers semantic edges, building the graph automatically as you write.",
      "The editor is built on TipTap, ProseMirror, with rich extensions for links, tasks, markdown, and drag handling. Graph visualization uses React Flow and react-force-graph-2d for navigating the knowledge space. All data lives locally in IndexedDB via Dexie. No server required. The application runs as a client-side Vite SPA deployed on Vercel."
    ],
    "links": [
      {
        "label": "Open dossier",
        "href": "/projects/noted"
      },
      {
        "label": "GitHub",
        "href": "https://github.com/kygura/noted"
      }
    ],
    "techStack": [
      "React",
      "TipTap",
      "React Flow",
      "OpenAI",
      "Dexie",
      "Vite"
    ],
    "layout": "standard",
    "status": "In development",
    "year": "2026"
  }
]
);
