/**
 * Build-time script: reads individual YAML project dossiers from
 * content/projects/ and generates the typed src/lib/project-dossiers.ts
 * module consumed by the React app.
 *
 * Usage:
 *   bun scripts/build-projects.ts
 *
 * This runs automatically as part of `bun run build` via the prebuild hook.
 */

import fs from "node:fs/promises";
import fss from "node:fs";
import path from "node:path";
import yaml from "js-yaml";
import { fileURLToPath } from "node:url";
import z from "zod";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PROJECTS_DIR = path.join(ROOT, "content", "projects");
const OUTPUT_MODULE = path.join(ROOT, "src", "lib", "project-dossiers.ts");

// ---- Schema -------------------------------------------------------------------

const projectLinkSchema = z.object({
  label: z.string().min(1),
  href: z.string().min(1),
});

const projectLayoutSchema = z.enum(["wide", "standard", "full"]);

const projectYamlSchema = z.object({
  accent: z.string().optional(),
  title: z.string().min(1),
  subtitle: z.string().min(1),
  summary: z.string().min(1),
  description: z.string().min(1),
  overview: z.array(z.string().min(1)).min(1),
  repo: z.string().url().optional(),
  live: z.string().url().optional(),
  techStack: z.array(z.string()).optional(),
  layout: projectLayoutSchema.default("standard"),
  status: z.string().min(1),
  year: z.string().min(1),
});

type ProjectYaml = z.infer<typeof projectYamlSchema>;

// ---- Slug helper ---------------------------------------------------------------

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

function uniqueLinks(links: { label: string; href: string }[]): { label: string; href: string }[] {
  const seen = new Set<string>();
  return links.filter((link) => {
    const key = `${link.label}:${link.href}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

// ---- Transform YAML → ProjectDraft -------------------------------------------

function yamlToDraft(slug: string, data: ProjectYaml) {
  const links: { label: string; href: string }[] = [
    { label: "Open dossier", href: `/projects/${slug}` },
  ];
  if (data.live) links.push({ label: "Live demo", href: data.live });
  if (data.repo) links.push({ label: "GitHub", href: data.repo.replace(/\.git$/, "") });

  return {
    slug,
    accent: data.accent,
    title: data.title,
    subtitle: data.subtitle,
    summary: data.summary,
    description: data.description,
    overview: data.overview,
    links: uniqueLinks(links),
    techStack: data.techStack,
    layout: data.layout,
    status: data.status,
    year: data.year,
  };
}

// ---- Main ---------------------------------------------------------------------

async function main() {
  console.log("build-projects: reading YAML dossiers from content/projects/");

  let files: string[];
  try {
    files = await fs.readdir(PROJECTS_DIR);
  } catch {
    console.error(`Cannot read directory: ${PROJECTS_DIR}`);
    process.exit(1);
  }

  const yamlFiles = files.filter((f) => f.endsWith(".yaml") || f.endsWith(".yml"));
  if (!yamlFiles.length) {
    console.warn("No YAML project files found. Writing empty module.");
    await writeModule([]);
    return;
  }

  const entries: object[] = [];
  const errors: string[] = [];

  for (const file of yamlFiles) {
    const slug = file.replace(/\.ya?ml$/, "");
    const filePath = path.join(PROJECTS_DIR, file);
    const raw = await fs.readFile(filePath, "utf-8");

    let data: unknown;
    try {
      data = yaml.load(raw);
    } catch (err) {
      errors.push(`${file}: YAML parse error — ${err instanceof Error ? err.message : err}`);
      continue;
    }

    const parsed = projectYamlSchema.safeParse(data);
    if (!parsed.success) {
      const issues = parsed.error.issues.map((i) => `${i.path.join(".")}: ${i.message}`).join("; ");
      errors.push(`${file}: validation error — ${issues}`);
      continue;
    }

    entries.push(yamlToDraft(slug, parsed.data));
  }

  if (errors.length > 0) {
    console.error("Errors encountered:");
    for (const err of errors) console.error(`  ✗ ${err}`);
    if (entries.length === 0) {
      console.error("No valid entries. Aborting.");
      process.exit(1);
    }
    console.warn(`Proceeding with ${entries.length} valid entries.`);
  }

  await writeModule(entries);
  console.log(`build-projects: wrote ${entries.length} project(s) to ${path.relative(ROOT, OUTPUT_MODULE)}`);
}

async function writeModule(entries: object[]) {
  const content = [
    "// Auto-generated by scripts/build-projects.ts — do not edit directly.",
    "// Source: content/projects/*.yaml",
    'import { defineProjects } from "./project-schema";',
    "",
    "export const projectDossiers = defineProjects(",
    JSON.stringify(entries, null, 2),
    ");",
    "",
  ].join("\n");

  await fs.writeFile(OUTPUT_MODULE, content, "utf-8");
}

await main();
